GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "users@gmail.com",
    "psw": "1234"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "users@gmail.com",
    "psw": "1234"
}